# Generated by Django 5.2.9 on 2026-09-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=255)),
                ('finding_type', models.CharField(choices=[('unused', 'Unused'), ('low_usage', 'Low Usage'), ('shadow_saas', 'Shadow SaaS'), ('redundant', 'Redundant')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('annual_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('potential_savings', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('evidence', models.JSONField(default=dict)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='organizations.organization')),
            ],
            options={
                'ordering': ['-potential_savings', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'finding_type'], name='findings_fi_organiz_a5e9bd_idx'), models.Index(fields=['organization', 'severity'], name='findings_fi_organiz_55b4e5_idx')],
            },
        ),
    ]
