# Generated by Django 5.2.9 on 2026-09-05 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extensions', '0002_alter_extensionenrollment_id'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(default='active_tab', max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='extensions.extensionenrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', 'domain', 'occurred_at'], name='usage_usage_organiz_55e7c7_idx'), models.Index(fields=['enrollment', 'occurred_at'], name='usage_usage_enrollm_d0e704_idx')],
            },
        ),
    ]
