# Generated by Django 5.2.9 on 2026-09-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_alter_extensionenrollment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionenrollment',
            name='extension_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
