# Generated by Django 5.2.9 on 2026-09-09 13:34

import apps.extensions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_extensionenrollment_extension_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionenrollment',
            name='expires_at',
            field=models.DateTimeField(default=apps.extensions.models.default_enrollment_expiration),
        ),
    ]
